# Generated by Django 5.0.6 on 2024-06-30 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado'), ('ALMACEN', 'Almacen'), ('ENVIO', 'Envio')], default='ALMACEN', max_length=20, verbose_name='estado')),
                ('telefono2', models.CharField(max_length=9, verbose_name='telefono2')),
                ('comuna2', models.CharField(max_length=50, verbose_name='comuna2')),
                ('direccion2', models.CharField(max_length=50, verbose_name='direccion2')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='fecha_emision')),
                ('carritoDeCompra', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mi_web.carritodecompras', verbose_name='CarritoDeCompra')),
                ('metodoDePago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mi_web.tarjeta', verbose_name='Tarjeta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
