# Generated by Django 5.0.6 on 2024-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0004_alter_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='nombre_receptor',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Nombre del Receptor'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='rut_receptor',
            field=models.CharField(default='00000000-0', max_length=12, verbose_name='RUT del Receptor'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ENVIO', 'Envio'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('ALMACEN', 'Almacen')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
    ]
