# Generated by Django 5.0.6 on 2024-06-30 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0006_alter_boleta_estado_alter_boleta_nombre_receptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='carritoDeCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mi_web.carritodecompras', verbose_name='CarritoDeCompra'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ENVIO', 'Envio'), ('ALMACEN', 'Almacen'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
