# Generated by Django 5.0.6 on 2024-07-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0008_alter_boleta_estado_productoboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_daneado',
            field=models.BooleanField(default=False, verbose_name='daneado'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ALMACEN', 'Almacen'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado'), ('ENVIO', 'Envio')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
    ]
