# Generated by Django 5.0.6 on 2024-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0009_usuario_es_daneado_alter_boleta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_daneado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_baneado',
            field=models.BooleanField(default=False, verbose_name='baneado'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('ALMACEN', 'Almacen'), ('CANCELADO', 'Cancelado'), ('ENVIO', 'Envio')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
    ]
