# Generated by Django 5.0.6 on 2024-07-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0010_remove_usuario_es_daneado_usuario_es_baneado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('ENVIO', 'Envio'), ('CANCELADO', 'Cancelado'), ('ALMACEN', 'Almacen')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(max_length=500, verbose_name='Razón del Bloqueo')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Bloqueo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo',
                'verbose_name_plural': 'Bloqueos',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
        migrations.CreateModel(
            name='Desbloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(max_length=500, verbose_name='Razón del Desbloqueo')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Desbloqueo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desbloqueo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desbloqueo',
                'verbose_name_plural': 'Desbloqueo',
                'ordering': ['-fecha_desbloqueo'],
            },
        ),
    ]
