# Generated by Django 5.0.6 on 2024-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0012_alter_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ENVIO', 'Envio'), ('ALMACEN', 'Almacen'), ('COMPLETADO', 'Completado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
    ]
