# Generated by Django 5.0.6 on 2024-07-05 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0014_alter_boleta_estado_reclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_web.boleta', verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ENVIO', 'Envio'), ('ALMACEN', 'Almacen'), ('COMPLETADO', 'Completado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('SERVICIO', 'Servicio'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
