# Generated by Django 5.0.6 on 2024-07-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0015_reclamo_boleta_alter_boleta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('ENVIO', 'Envio'), ('CANCELADO', 'Cancelado'), ('ALMACEN', 'Almacen')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('OTRO', 'Otro'), ('SERVICIO', 'Servicio')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
