# Generated by Django 5.0.6 on 2024-07-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0016_alter_boleta_estado_alter_reclamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('ALMACEN', 'Almacen'), ('CANCELADO', 'Cancelado'), ('ENVIO', 'Envio')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripción',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.boleta', verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
