# Generated by Django 5.0.6 on 2024-07-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0017_alter_boleta_estado_alter_producto_descripción_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ALMACEN', 'Almacen'), ('ENVIO', 'Envio'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('SERVICIO', 'Servicio'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
