# Generated by Django 5.0.6 on 2024-07-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0018_alter_boleta_estado_alter_reclamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ALMACEN', 'Almacen'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado'), ('ENVIO', 'Envio')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='productoboleta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.producto'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
