# Generated by Django 5.0.6 on 2024-07-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0019_alter_boleta_estado_alter_productoboleta_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ENVIO', 'Envio'), ('ALMACEN', 'Almacen'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='productoboleta',
            name='producto',
            field=models.CharField(max_length=50, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('SERVICIO', 'Servicio'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
