# Generated by Django 5.0.6 on 2024-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0021_alter_boleta_estado_alter_reclamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ALMACEN', 'Almacen'), ('ENVIO', 'Envio'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('SERVICIO', 'Servicio'), ('PRODUCTO', 'Producto'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
    ]
