# Generated by Django 5.0.6 on 2024-07-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0023_alter_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ALMACEN', 'Almacen'), ('ENVIO', 'Envio'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tarjeta_de_credito',
            field=models.IntegerField(max_length=16, unique=True, verbose_name='numero tarjeta'),
        ),
    ]
