# Generated by Django 5.0.6 on 2024-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0024_alter_boleta_estado_alter_reclamo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ALMACEN', 'Almacen'), ('COMPLETADO', 'Completado'), ('ENVIO', 'Envio'), ('CANCELADO', 'Cancelado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo',
            field=models.CharField(choices=[('SERVICIO', 'Servicio'), ('OTRO', 'Otro'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de reclamo'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='codigo_de_seguridad',
            field=models.CharField(max_length=3, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_de_vencimiento',
            field=models.CharField(max_length=5, verbose_name='fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tarjeta_de_credito',
            field=models.CharField(max_length=16, unique=True, verbose_name='numero tarjeta'),
        ),
    ]
