# Generated by Django 5.0.6 on 2024-07-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0025_alter_boleta_estado_alter_reclamo_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('ENVIO', 'Envio'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado'), ('ALMACEN', 'Almacen')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.provincia', verbose_name='provincia')),
            ],
            options={
                'unique_together': {('nombre', 'provincia')},
            },
        ),
    ]
