# Generated by Django 5.0.6 on 2024-07-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0029_alter_boleta_estado_alter_reclamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('ENVIO', 'Envio'), ('ALMACEN', 'Almacen'), ('CANCELADO', 'Cancelado')], default='ALMACEN', max_length=20, verbose_name='estado'),
        ),
    ]
