<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Aadir producto_card-img-top</name>
   <tag></tag>
   <elementGuidId>4c65d6ec-cf7a-4c13-9eff-f93fffe8ef4e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Auto eléctrico']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Auto eléctrico&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>354aa7fc-6a18-4b03-82a9-ea2d36c41257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>0154597e-8dce-474a-a03b-2a0cd86ab04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/media/producto/Electaurus.png</value>
      <webElementGuid>a1b19700-7e23-4b6b-9ba1-0a8830aa1e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Auto eléctrico</value>
      <webElementGuid>a4f878ba-1a9b-412b-a0dd-d604f3cb49da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;py-5 col-md-12&quot;]/div[@class=&quot;container px-4 px-lg-5&quot;]/div[@class=&quot;row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center&quot;]/div[@class=&quot;col mb-5&quot;]/div[@class=&quot;card h-100&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>86bf2e1a-15c8-4dcb-a9ae-b4f04f3a620a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Auto eléctrico']</value>
      <webElementGuid>ef310d07-db26-4794-ba3f-0f0bbeff55d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>895c589c-9f51-4170-af20-5cb9edbcd2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/media/producto/Electaurus.png' and @alt = 'Auto eléctrico']</value>
      <webElementGuid>24a770a9-9725-416d-afe2-5163d1c18249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
