<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__precio</name>
   <tag></tag>
   <elementGuidId>5c1c0328-dc2f-4117-80bd-b3b7cfe5adb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#precio_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='precio_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Precio*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05ee9de6-651e-4483-81d6-abcf775fd57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dfe9aeae-75b8-44a8-8936-f7b4224f3849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precio</value>
      <webElementGuid>ba6e9a24-d87c-45df-9c63-0d824e6e78f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5a8b0ed-4695-436f-8da8-1bf8e27ae2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>precio_id</value>
      <webElementGuid>92a0bf87-04b8-4b24-8cf4-7ee2e0fb5899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numberinput form-control</value>
      <webElementGuid>94a6c2d3-0cdc-4cf5-80db-59e43380c321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;precio_id&quot;)</value>
      <webElementGuid>2579d368-c8b1-4dd8-a03a-4c22e7572fd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='precio_id']</value>
      <webElementGuid>74ee0591-c001-4238-abbe-650d06927c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_precio']/input</value>
      <webElementGuid>cee23809-775d-4d7d-862a-135fe12d32ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>467304b9-11fa-4ddd-a5a8-2d3c2bf58023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'precio' and @id = 'precio_id']</value>
      <webElementGuid>7fcc225d-d536-4910-9697-2b43b755cc66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
