<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__descripcin</name>
   <tag></tag>
   <elementGuidId>65f823d5-46a4-42f0-ab2f-0b87cd0407c3</elementGuidId>
   <imagePath>../mi_web/static/vet/img/Electaurus.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_descripción</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_descripción']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>../mi_web/static/vet/img/Electaurus.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Descripción*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69fd7e10-90a3-4db4-a6bc-61c8742a17c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7dbffc92-06bc-4c77-8fd8-4cac4481fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>descripción</value>
      <webElementGuid>2ff84735-a7e9-4b21-99de-494ec6703953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>75039f74-1485-4501-ac90-03c2e43c0579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput form-control</value>
      <webElementGuid>74e4d188-41e7-4468-8fdd-d41026f4b305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_descripción</value>
      <webElementGuid>fb302cce-385b-4558-b3b8-5eae4800fe75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_descripción&quot;)</value>
      <webElementGuid>94039e09-f145-4c46-a1ea-e8c1026ecc17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_descripción']</value>
      <webElementGuid>5f233820-02f0-4860-b744-a5eff83886fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_descripción']/input</value>
      <webElementGuid>5bf362c9-4dff-4aa7-8c07-abe7383b9b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>216f8764-6801-4fc1-986b-586d47d6c380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'descripción' and @id = 'id_descripción']</value>
      <webElementGuid>f8e6b493-3bf1-49b2-aff6-9c5ddc13dd38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
