<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__descripcin</name>
   <tag></tag>
   <elementGuidId>a3570158-30c4-4e09-8be5-ac2634674424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descripción_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='descripción_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Descripción*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ea18924-b9b5-4098-ba7d-ed5c57264215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9da24952-01e5-4e96-bc69-6de4cd5c1b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>descripción</value>
      <webElementGuid>59b5f5d9-33ac-4caf-bd43-1ec7dbe44043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>auto en estado indescriptible Detalle: no anda</value>
      <webElementGuid>1e42a36b-0836-4ccd-8d7f-f97cc0c07277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>81f5ab3f-788f-4eb8-9614-3084bbc8dec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descripción_id</value>
      <webElementGuid>8eaf7a8f-0e72-4f66-9902-9f969622c244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput form-control</value>
      <webElementGuid>e27f99f5-9609-4f82-8ec8-d4998ce7fceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descripción_id&quot;)</value>
      <webElementGuid>70950a8b-031c-471b-b505-321c912193cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='descripción_id']</value>
      <webElementGuid>eaa3da6c-b24e-49cd-bdb4-a1a72c77209a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_descripción']/input</value>
      <webElementGuid>4bf64a9f-7e1f-4d49-a59a-c8f245cfaa72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ade0e199-f66e-4531-8ec7-1952c2ff6351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'descripción' and @id = 'descripción_id']</value>
      <webElementGuid>d0c8cae2-66a7-49f8-8eb2-8692b8944dd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
