<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nombre</name>
   <tag></tag>
   <elementGuidId>3a0b6610-3b38-47eb-ba87-bff5d6e9276c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nombre_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nombre_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nombre*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>495fba4a-511b-4a25-8995-a57b443d738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01dd57a6-48d5-4185-9f28-35fc0d95eb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>deea3199-3b39-4aba-9359-72909ea69e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cacharro</value>
      <webElementGuid>022480c7-e960-444a-aa23-56f8d22f4d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7f31bb0d-6d13-4640-99df-ea967d11e1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombre_id</value>
      <webElementGuid>23a253b0-16a3-4699-9ea8-c382e209b6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput form-control</value>
      <webElementGuid>90b99fc3-e681-4baa-bee9-edf6d33ffe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nombre_id&quot;)</value>
      <webElementGuid>cbe384c0-399d-4fda-89bd-afad4e807624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nombre_id']</value>
      <webElementGuid>80be5676-64bb-4fa4-87fb-4ddec0540779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_nombre']/input</value>
      <webElementGuid>28c061e8-ca6c-45c6-b709-1af4640f057c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7265fa40-b120-461e-9fbe-c7ea9a38724a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nombre' and @id = 'nombre_id']</value>
      <webElementGuid>8007ee97-0c8a-4c57-97ca-acfa7d0a39ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
