<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__precio</name>
   <tag></tag>
   <elementGuidId>5a80cb15-c764-41ad-9947-43f6ba47db1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#precio_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='precio_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Precio*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e650f3a6-9efb-403c-a0c3-657bf35eb14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9961697e-ea84-467e-bed7-b6d66ff1f9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precio</value>
      <webElementGuid>c0dd693c-3145-43ff-a65e-a6f4f809eb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>fb38064b-1f07-47a2-8bf9-6ed65b59c868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>precio_id</value>
      <webElementGuid>b7a5ab11-6afd-4c4a-b038-ec84bd08af3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numberinput form-control</value>
      <webElementGuid>32ff5bf4-e3df-4a0a-9002-e9c461de2362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;precio_id&quot;)</value>
      <webElementGuid>400789a3-fc04-417c-8d09-f9143e2694aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='precio_id']</value>
      <webElementGuid>e6ed4656-b9f8-4e70-8708-3d5aba57b7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_precio']/input</value>
      <webElementGuid>b7eca699-3840-45b5-b252-f29946cd7370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>6a73468d-fcdb-45aa-95ce-efb8dfe6b380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'precio' and @id = 'precio_id']</value>
      <webElementGuid>1f3942ea-f0da-4f3a-8bd3-5f53e087aa68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
